"""Wire lane: parsers checked against checked-in NDJSON bodies.

The fixtures under ``fixtures/`` are generated by :mod:`tests.wire.build_fixtures` (run
``uv run python tests/wire/build_fixtures.py`` after changing it) and contain real base64 Arrow
IPC payloads framed exactly as documented in ``docs/CONTRACT_NOTES.md`` §2.2.
"""

from __future__ import annotations

from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"


def read_fixture(name: str) -> bytes:
    """Read one checked-in NDJSON fixture body, bytes-exact (trailing framing included)."""
    return (FIXTURES_DIR / name).read_bytes()
